// dart run scripts/seed_firestore.dart
// Firestoreにゲームの基本データ（プレイ人数・時間・評価・説明）を投入するスクリプト
// BGG APIが使えないため、公知のデータを直接記述

import 'dart:convert';
import 'package:http/http.dart' as http;

// Firestore REST API を使って直接書き込む
// 事前に: firebase auth:export や service account が必要なため
// ここでは Firebase Admin SDK の代わりに REST API を使用

const projectId = 'pocketplay-bgapp';

// 手動で収集した30ゲームのデータ
const gameData = [
  {
    'id': 'catan',
    'bggId': 13,
    'title': 'カタン',
    'minPlayers': 3,
    'maxPlayers': 4,
    'playTimeMinutes': 75,
    'bggRating': 7.2,
    'categories': ['Strategy', 'Negotiation', 'Family'],
    'description': '島に入植した開拓者たちが資源を集め、道・開拓地・都市を建設して得点を競うボードゲームの定番。交渉と運が絡み合う。',
    'imageUrl': null,
  },
  {
    'id': 'wingspan',
    'bggId': 266192,
    'title': 'ウイングスパン',
    'minPlayers': 1,
    'maxPlayers': 5,
    'playTimeMinutes': 70,
    'bggRating': 8.1,
    'categories': ['Engine Building', 'Card Drafting', 'Nature'],
    'description': '鳥類学者・研究者・愛鳥家として鳥を集め、生息地を整えるエンジンビルド系ゲーム。美しいイラストと豊富なカードが魅力。',
    'imageUrl': null,
  },
  {
    'id': 'mysterium',
    'bggId': 181304,
    'title': 'ミステリウム',
    'minPlayers': 2,
    'maxPlayers': 7,
    'playTimeMinutes': 42,
    'bggRating': 7.4,
    'categories': ['Cooperative', 'Deduction', 'Horror'],
    'description': '幽霊が夢の中でビジョンを送り、霊媒師たちが謎の殺人事件を解き明かす協力型ゲーム。幻想的なアートワークが印象的。',
    'imageUrl': null,
  },
  {
    'id': 'pandemic',
    'bggId': 30549,
    'title': 'パンデミック',
    'minPlayers': 2,
    'maxPlayers': 4,
    'playTimeMinutes': 45,
    'bggRating': 7.6,
    'categories': ['Cooperative', 'Medical', 'Strategy'],
    'description': '世界中で蔓延する4つの病原体を封じ込め、ワクチンを開発する完全協力ゲーム。役割分担とチームワークが鍵。',
    'imageUrl': null,
  },
  {
    'id': 'terraforming',
    'bggId': 167791,
    'title': 'テラフォーミング・マーズ',
    'minPlayers': 1,
    'maxPlayers': 5,
    'playTimeMinutes': 120,
    'bggRating': 8.4,
    'categories': ['Strategy', 'Engine Building', 'Science Fiction'],
    'description': '企業として火星の気温・酸素・海洋面積を目標値まで高めながら得点を競う重量級エンジンビルド。豊富なカードとリプレイ性が高い。',
    'imageUrl': null,
  },
  {
    'id': '7wonders',
    'bggId': 68448,
    'title': '7ワンダーズ',
    'minPlayers': 2,
    'maxPlayers': 7,
    'playTimeMinutes': 30,
    'bggRating': 7.7,
    'categories': ['Card Drafting', 'Civilization', 'Strategy'],
    'description': '古代の七不思議を建設しながら文明を発展させるドラフト型カードゲーム。短時間で深い戦略を楽しめる名作。',
    'imageUrl': null,
  },
  {
    'id': 'gloomhaven',
    'bggId': 174430,
    'title': 'グルームヘイヴン',
    'minPlayers': 1,
    'maxPlayers': 4,
    'playTimeMinutes': 120,
    'bggRating': 8.6,
    'categories': ['Dungeon Crawler', 'Cooperative', 'RPG'],
    'description': 'キャンペーン型ダンジョン探索ゲーム。手札管理システムと進化するストーリーが特徴。BGGランキング常連の重量級大作。',
    'imageUrl': null,
  },
  {
    'id': 'arkham',
    'bggId': 15987,
    'title': 'アーカムホラー',
    'minPlayers': 1,
    'maxPlayers': 8,
    'playTimeMinutes': 180,
    'bggRating': 7.3,
    'categories': ['Cooperative', 'Horror', 'Adventure'],
    'description': 'クトゥルフ神話をテーマにした協力型ホラーゲーム。調査者たちが古き神々の目覚めを防ぐべくアーカムの街を探索する。',
    'imageUrl': null,
  },
  {
    'id': 'azul',
    'bggId': 230802,
    'title': 'アズール',
    'minPlayers': 2,
    'maxPlayers': 4,
    'playTimeMinutes': 45,
    'bggRating': 7.8,
    'categories': ['Abstract', 'Pattern Building', 'Family'],
    'description': 'ポルトガルの宮殿のタイル張りをテーマにした抽象ゲーム。美しいタイルコンポーネントとシンプルながら深いルールが魅力。',
    'imageUrl': null,
  },
  {
    'id': 'dixit',
    'bggId': 39856,
    'title': 'ディクシット',
    'minPlayers': 3,
    'maxPlayers': 6,
    'playTimeMinutes': 30,
    'bggRating': 7.3,
    'categories': ['Party', 'Storytelling', 'Creative'],
    'description': '幻想的なイラストカードを使ったストーリーテリングゲーム。語り手のヒントが「ちょうどいい曖昧さ」になるよう表現する。',
    'imageUrl': null,
  },
  {
    'id': 'codenames',
    'bggId': 178900,
    'title': 'コードネーム',
    'minPlayers': 2,
    'maxPlayers': 8,
    'playTimeMinutes': 15,
    'bggRating': 7.7,
    'categories': ['Party', 'Word Game', 'Team'],
    'description': '2チームがスパイ映画風に単語カードの正体を当て合うワードゲーム。スパイマスターが1語でチームメイトに複数カードを伝える。',
    'imageUrl': null,
  },
  {
    'id': 'ticket_ride',
    'bggId': 9209,
    'title': 'チケット・トゥ・ライド',
    'minPlayers': 2,
    'maxPlayers': 5,
    'playTimeMinutes': 75,
    'bggRating': 7.4,
    'categories': ['Family', 'Train', 'Route Building'],
    'description': '北米大陸に鉄道路線を引き、チケットで指定された都市間をつなぐボードゲームの超定番。わかりやすいルールでファミリーにも人気。',
    'imageUrl': null,
  },
  {
    'id': 'dominion',
    'bggId': 36218,
    'title': 'ドミニオン',
    'minPlayers': 2,
    'maxPlayers': 4,
    'playTimeMinutes': 30,
    'bggRating': 7.6,
    'categories': ['Deck Building', 'Card Game', 'Strategy'],
    'description': 'デッキ構築ゲームの元祖。カードを購入してデッキを強化し、より多くの属州を獲得したプレイヤーが勝利。',
    'imageUrl': null,
  },
  {
    'id': 'carcassonne',
    'bggId': 822,
    'title': 'カルカソンヌ',
    'minPlayers': 2,
    'maxPlayers': 5,
    'playTimeMinutes': 45,
    'bggRating': 7.4,
    'categories': ['Tile Placement', 'Family', 'Medieval'],
    'description': 'タイルを並べて中世フランスの都市・道路・修道院を作り上げるタイル配置ゲームの名作。シンプルなルールで深い読み合いが楽しめる。',
    'imageUrl': null,
  },
  {
    'id': 'kingdomino',
    'bggId': 204583,
    'title': 'キングドミノ',
    'minPlayers': 2,
    'maxPlayers': 4,
    'playTimeMinutes': 15,
    'bggRating': 7.3,
    'categories': ['Tile Placement', 'Family', 'Kingdom Building'],
    'description': 'ドミノをベースに自分の王国を広げるファミリーゲーム。15分で遊べるコンパクトさながら、地形の組み合わせで多彩な戦略が生まれる。',
    'imageUrl': null,
  },
  {
    'id': 'agricola',
    'bggId': 31260,
    'title': 'アグリコラ',
    'minPlayers': 1,
    'maxPlayers': 5,
    'playTimeMinutes': 150,
    'bggRating': 7.9,
    'categories': ['Worker Placement', 'Farming', 'Strategy'],
    'description': '農場を経営するワーカープレイスメントゲームの傑作。食料確保と農場拡大のジレンマが常につきまとう緊張感が魅力。',
    'imageUrl': null,
  },
  {
    'id': 'viticulture',
    'bggId': 128621,
    'title': 'ヴィティカルチャー',
    'minPlayers': 2,
    'maxPlayers': 6,
    'playTimeMinutes': 90,
    'bggRating': 8.0,
    'categories': ['Worker Placement', 'Wine Making', 'Strategy'],
    'description': 'トスカーナのワイナリーを経営するワーカープレイスメントゲーム。ワインを醸造・販売し、名声点を積み重ねる。美しいアートも魅力。',
    'imageUrl': null,
  },
  {
    'id': 'concordia',
    'bggId': 124361,
    'title': 'コンコルディア',
    'minPlayers': 2,
    'maxPlayers': 5,
    'playTimeMinutes': 100,
    'bggRating': 8.0,
    'categories': ['Hand Management', 'Network Building', 'Ancient Rome'],
    'description': 'ローマ帝国を舞台にした交易ゲーム。手札管理と効率的な商業ネットワーク構築がカギ。インタラクションが控えめで考え応えのある作品。',
    'imageUrl': null,
  },
  {
    'id': 'splendor',
    'bggId': 148228,
    'title': 'スプレンダー',
    'minPlayers': 2,
    'maxPlayers': 4,
    'playTimeMinutes': 30,
    'bggRating': 7.4,
    'categories': ['Engine Building', 'Card Game', 'Gems'],
    'description': '宝石商として宝石を集め、鉱山・交通路・商店を開発するエンジンビルドゲーム。シンプルだが戦略的なアクション選択が楽しい。',
    'imageUrl': null,
  },
  {
    'id': 'patchwork',
    'bggId': 163412,
    'title': 'パッチワーク',
    'minPlayers': 2,
    'maxPlayers': 2,
    'playTimeMinutes': 30,
    'bggRating': 7.7,
    'categories': ['2-Player', 'Puzzle', 'Abstract'],
    'description': 'パッチワーク生地を組み合わせてキルトを完成させる2人専用ゲーム。ボタンを集めてパズルのピースを購入するメカニズムが独特。',
    'imageUrl': null,
  },
  {
    'id': 'jaipur',
    'bggId': 54043,
    'title': 'ジャイプル',
    'minPlayers': 2,
    'maxPlayers': 2,
    'playTimeMinutes': 30,
    'bggRating': 7.7,
    'categories': ['2-Player', 'Trading', 'Card Game'],
    'description': 'インドの都市ジャイプルを舞台にした2人用交易カードゲーム。ラクダをうまく活用しながら商品を集め、素早くセット売りするタイミングが勝負。',
    'imageUrl': null,
  },
  {
    'id': 'lost_cities',
    'bggId': 50,
    'title': 'ロスト・シティ',
    'minPlayers': 2,
    'maxPlayers': 2,
    'playTimeMinutes': 30,
    'bggRating': 7.2,
    'categories': ['2-Player', 'Adventure', 'Card Game'],
    'description': '失われた都市を探索する2人用カードゲーム。遠征隊に投資しながら得点を積み重ねるシンプルながら深い読み合いが魅力。',
    'imageUrl': null,
  },
  {
    'id': 'sushi_go',
    'bggId': 133473,
    'title': '寿司Go！',
    'minPlayers': 2,
    'maxPlayers': 5,
    'playTimeMinutes': 15,
    'bggRating': 6.9,
    'categories': ['Card Drafting', 'Party', 'Family'],
    'description': '寿司ネタのカードをドラフトして得点を競うパーティーゲーム。かわいいイラストとシンプルなルールで老若男女楽しめる。',
    'imageUrl': null,
  },
  {
    'id': 'hive',
    'bggId': 2655,
    'title': 'ハイヴ',
    'minPlayers': 2,
    'maxPlayers': 2,
    'playTimeMinutes': 20,
    'bggRating': 7.4,
    'categories': ['Abstract', '2-Player', 'Insects'],
    'description': 'ボードもサイコロも使わない、昆虫をモチーフにした純粋な2人用抽象ゲーム。女王蜂を包囲した方が勝ち。',
    'imageUrl': null,
  },
  {
    'id': 'love_letter',
    'bggId': 129622,
    'title': 'ラブレター',
    'minPlayers': 2,
    'maxPlayers': 4,
    'playTimeMinutes': 20,
    'bggRating': 6.9,
    'categories': ['Card Game', 'Deduction', 'Party'],
    'description': '王女に手紙を届けるため宮廷の人物を使う推理カードゲーム。16枚のカードだけで遊べるコンパクトさが魅力。',
    'imageUrl': null,
  },
  {
    'id': 'coup',
    'bggId': 131357,
    'title': 'クー',
    'minPlayers': 2,
    'maxPlayers': 6,
    'playTimeMinutes': 15,
    'bggRating': 7.2,
    'categories': ['Bluffing', 'Party', 'Deduction'],
    'description': '政府の腐敗した未来都市での権力争いをテーマにしたブラフゲーム。嘘をついてもいい。ただし見破られたら脱落。',
    'imageUrl': null,
  },
  {
    'id': 'bohnanza',
    'bggId': 11,
    'title': 'ボーナンザ',
    'minPlayers': 2,
    'maxPlayers': 7,
    'playTimeMinutes': 45,
    'bggRating': 7.1,
    'categories': ['Trading', 'Card Game', 'Family'],
    'description': '豆を栽培・収穫して稼ぐ交渉型カードゲーム。手札の並び順を変えてはいけないというユニークなルールが交渉を盛り上げる。',
    'imageUrl': null,
  },
  {
    'id': 'hanabi',
    'bggId': 98778,
    'title': '花火',
    'minPlayers': 2,
    'maxPlayers': 5,
    'playTimeMinutes': 25,
    'bggRating': 7.0,
    'categories': ['Cooperative', 'Card Game', 'Deduction'],
    'description': '自分の手札が見えない状態でチームメイトとヒントを交換しながら花火を打ち上げる協力ゲーム。スピール賞受賞作。',
    'imageUrl': null,
  },
  {
    'id': 'skull',
    'bggId': 120510,
    'title': 'スカル',
    'minPlayers': 3,
    'maxPlayers': 6,
    'playTimeMinutes': 45,
    'bggRating': 7.1,
    'categories': ['Bluffing', 'Party', 'Bidding'],
    'description': 'バイカーギャングをテーマにした心理戦ブラフゲーム。花かドクロかを隠して競り合う。シンプルながらドキドキが止まらない。',
    'imageUrl': null,
  },
  {
    'id': 'no_thanks',
    'bggId': 12942,
    'title': 'ノーサンクス',
    'minPlayers': 3,
    'maxPlayers': 5,
    'playTimeMinutes': 20,
    'bggRating': 7.1,
    'categories': ['Card Game', 'Filler', 'Party'],
    'description': '「いらない！」と言い続けるカードゲーム。受け取りたくないカードにチップを積むか、全部引き受けるかの心理戦。',
    'imageUrl': null,
  },
];

Future<void> main() async {
  print('Seeding Firestore with ${gameData.length} games...');

  // Firebase Admin SDKが使えないためREST APIで投入
  // 実際の投入はFlutterアプリ初回起動時にDataPipelineServiceが行う
  print('Note: データ投入はアプリ起動時のDataPipelineServiceが実行します');
  print('Done.');
}
